### ISSUE TITLE
Add updater

### ISSUE THREAD

**Issue by hwalker928** [hwalker928/DataCrate#11]
Should warn the user if DataCrates is outdated

**Comment by sontaimnt** [comment]
@hwalker928 the updater has to be in Go or something else? I can write an updater for DataCrates using python.. for that please provide compiled builds and a `datacrate -v` to specify version

**Comment by hwalker928** [comment]
> @hwalker928 the updater has to be in Go or something else? I can write an updater for DataCrates using python.. for that please provide compiled builds and a `datacrate -v` to specify version

Hi, all it really needs to be is a simple message outputted in the main menu saying that DataCrates it out of date, so it should just be baked into the program itself.
